### ISSUE TITLE
reverse orientation of transcripts on minus strand

### ISSUE THREAD

**Issue by tabeariepe** [dzhang32/ggtranscript#11]
Hi, 

Is there an easy way to inverse the orientation for transcripts that are on the minus strand (to also go from left to right)?

Kind regards, 
Tabea

**Comment by Jbrenton191** [comment]
Hi Tabea,

You can flip the x coordiantes by using coord_cartesian(xlim = c(x, y)). Just change the order of x and y if it is on the minus strand.

I hope that helps.

Jon

**Comment by dzhang32** [comment]
Thanks a lot for the tip @Jbrenton191! Closing this as resolved, happy to reopen if not.
