### ISSUE TITLE
shortened gaps with exon and CDS

### ISSUE THREAD

**Issue by kenneditodd** [dzhang32/ggtranscript#12]
Is there a way to create a plot with shortened gaps that still shows exon vs CDS regions?

**Comment by dzhang32** [comment]
Apologies for super slow response! I think the [add_utr()](https://dzhang32.github.io/ggtranscript/reference/add_utr.html) example covers what you are looking for here. 

I will close this for now, but happy to reopen if you are still having this issue and it is not solved via the above.
