### ISSUE TITLE
"Size" aesthetic

### ISSUE THREAD

**Issue by EmilVorsteveld** [dzhang32/ggtranscript#13]
When plotting the SOD1 transcripts, as in the package tutorial (https://dzhang32.github.io/ggtranscript/articles/ggtranscript.html):
sod1_exons %>% ggplot(aes(xstart = start, xend = end, y = transcript_name)) +
  geom_range(aes(fill = transcript_biotype)) +
  geom_intron(data = to_intron(sod1_exons, "transcript_name"), aes(strand = strand))

I am getting the following warning:

"Using the `size` aesthetic in this geom was deprecated in ggplot2 3.4.0.
ℹ Please use `linewidth` in the `default_aes` field and elsewhere instead."

This aes is present in both the geom_range() and geom_intron() functions.

**Comment by dzhang32** [comment]
Thanks for raising, this should be fixed now!
